"""Render a `nature-review-studio` payload into a Markdown file (V1.4).

Same structure as the docx renderer, but emits a clean .md file that can be
opened in any text editor, pasted into chat, or converted with pandoc. The
markdown uses the same headings, the same numbering, the same English/Chinese
bilingual labels, and the same mojibake sanitizer as the docx path.

CLI:
    python render_review_md.py --payload <payload.json> --out <out.md>
    python render_review_md.py --payload <payload.json>           # default path
"""
from __future__ import annotations
import os

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


def _nrs_root() -> Path:
    env = os.environ.get("NRS_ROOT") or os.environ.get("NRL_ROOT")
    if env:
        return Path(env).resolve()
    here = Path(__file__).resolve().parent
    for ancestor in [here, *here.parents]:
        if (ancestor / "knowledge").is_dir() and (ancestor / "skill").is_dir():
            return ancestor
    return here.parent


_NRS_ROOT = _nrs_root()


TITLES = {
    "en": {
        "editor_letter_prefix": "Editor letter",
        "reviewer_section": "Reviewer",
        "overall": "Overall",
        "major": "Major concerns",
        "minor": "Minor concerns",
        "consensus": "Cross-review consensus",
        "task_table": "Revision task table",
        "confidence": "Confidence",
        "footer": "Generated by nature-review-studio",
        "no_consensus": "No concerns are shared by >=2 reviewers. Reviewers mostly agreed on small points.",
        "title": "Manuscript review",
    },
    "zh": {
        "editor_letter_prefix": "编辑信",
        "reviewer_section": "审稿人",
        "overall": "整体点评",
        "major": "主要问题",
        "minor": "次要问题",
        "consensus": "跨审稿意见综合",
        "task_table": "修订任务表",
        "confidence": "置信度",
        "footer": "由 nature-review-studio 生成",
        "no_consensus": "没有 >=2 位审稿人共同关心的问题。审稿人之间仅在细节上存在一致。",
        "title": "论文审稿意见",
    },
}

REVISION_BAND_ORDER = {
    "Major revision": ("Major revision", "重大修改"),
    "Accept with minor revisions": ("Accept with minor revisions", "接收（小修）"),
    "Reject in present form": ("Reject in present form", "本稿拒收"),
    "Cannot be assessed": ("Cannot be assessed", "无法评估"),
}


# ----- Sanitizer (same as docx path) -------------------------------

_MOJI_RE = re.compile(r"[\uE000-\uF8FF\uFFF0-\uFFFF]")
_CTRL_RE = re.compile(r"[\u0000-\u0008\u000B-\u001F\u007F]")


def s(text) -> str:
    if text is None:
        return ""
    text = str(text)
    text = _CTRL_RE.sub("", text)
    text = _MOJI_RE.sub("[?]", text)
    return text


def escape_md(text: str) -> str:
    """Escape markdown metacharacters that are not part of intended formatting."""
    # We only need to escape | inside table cells, otherwise plain text is fine.
    return text.replace("|", "\\|").replace("\n", " ")


# ----- Render --------------------------------------------------------

def render_markdown(payload: Dict[str, Any]) -> str:
    entry = payload["entry"]
    case_id = payload["case_id"]
    lang = payload["language"]
    T = TITLES[lang]

    lines: List[str] = []

    # Title
    lines.append(f"# {T['title']}")
    lines.append("")
    lines.append(f"*Case: {case_id}*")
    lines.append("")

    # Editor letter
    el = payload["editor_letter"]
    band = el["revision_level"]
    band_disp = REVISION_BAND_ORDER[band][0 if lang == "en" else 1]
    lines.append(f"## {T['editor_letter_prefix']} — {band_disp}")
    lines.append("")
    for para in el.get("paragraphs", []):
        if not para or not para.strip():
            continue
        lines.append(s(para).strip())
        lines.append("")

    # Reviewers
    for i, r in enumerate(payload.get("reviewers") or []):
        lines.append(f"## {T['reviewer_section']} {chr(ord('A') + i)} — {s(r.get('role_label',''))}")
        lines.append("")
        lines.append(f"### {T['overall']}")
        lines.append("")
        lines.append(s(r.get("overall_paragraph", "")).strip())
        lines.append("")

        majors = r.get("major_concerns") or []
        if majors:
            lines.append(f"### {T['major']}")
            lines.append("")
            for idx, c in enumerate(majors, start=1):
                head = s(c.get("heading", "")).rstrip(":.。 ").strip()
                body = s(c.get("body", "")).strip()
                anchor = c.get("evidence_pointer")
                lines.append(f"#### {idx}. {head}")
                lines.append("")
                if anchor:
                    sep = " " if body.endswith((".", "。", "!", "?")) else ". "
                    lines.append(f"{body}{sep}***{s(anchor)}***")
                else:
                    lines.append(body)
                lines.append("")

        minors = r.get("minor_concerns") or []
        if minors:
            lines.append(f"### {T['minor']}")
            lines.append("")
            for idx, c in enumerate(minors, start=1):
                head = s(c.get("heading", "")).rstrip(":.。 ").strip()
                body = s(c.get("body", "")).strip()
                anchor = c.get("evidence_pointer")
                lines.append(f"#### {idx}. {head}")
                lines.append("")
                if anchor:
                    sep = " " if body.endswith((".", "。", "!", "?")) else ". "
                    lines.append(f"{body}{sep}***{s(anchor)}***")
                else:
                    lines.append(body)
                lines.append("")

        if r.get("overall_confidence"):
            lines.append(f"**{T['confidence']}: {s(r['overall_confidence'])}.**")
            lines.append("")

    # Consensus
    lines.append(f"## {T['consensus']}")
    lines.append("")
    consensus = payload.get("consensus_block") or []
    if not consensus:
        lines.append(T["no_consensus"])
        lines.append("")
    else:
        for c in consensus:
            cid = s(c.get("id", "")).strip()
            desc = s(c.get("description", "")).strip()
            lines.append(f"#### {cid}. {desc}")
            lines.append("")
            meta = []
            if c.get("raised_by"):
                rb = ", ".join(s(x) for x in c["raised_by"])
                meta.append(f"raised by: {rb}" if lang == "en" else f"由以下审稿人提出: {rb}")
            if c.get("axis"):
                meta.append(f"axis: {s(c['axis'])}" if lang == "en" else f"轴: {s(c['axis'])}")
            if c.get("severity"):
                meta.append(f"severity: {s(c['severity'])}" if lang == "en" else f"严重程度: {s(c['severity'])}")
            if meta:
                lines.append("  ·  ".join(meta))
                lines.append("")
            if c.get("rationale"):
                lines.append(s(c["rationale"]))
                lines.append("")

    # Task table
    tt = payload.get("revision_task_table") or {}
    if tt and tt.get("headers") and tt.get("rows"):
        lines.append(f"## {T['task_table']}")
        lines.append("")
        headers = [escape_md(s(h)) for h in tt["headers"]]
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("|" + "|".join(["---"] * len(headers)) + "|")
        for row in tt["rows"]:
            cells = [escape_md(s(v)) for v in row]
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

    # Footer
    today = datetime.now().strftime("%Y-%m-%d")
    lines.append("---")
    lines.append(f"*{T['footer']}  ·  {today}  ·  {case_id}*")
    lines.append("")

    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--payload", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    with open(args.payload, "rb") as f:
        raw = f.read()
    if raw[:3] == b"\xef\xbb\xbf":
        raw = raw[3:]
    payload = json.loads(raw.decode("utf-8"))

    if not args.out:
        today = datetime.now().strftime("%Y%m%d")
        out_dir = _NRS_ROOT / "output"
        args.out = str(out_dir / f"{payload['entry']}_{payload['case_id']}_{today}.md")

    md = render_markdown(payload)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"[ok] wrote {out_path}  ({len(md)} chars, {len(md.splitlines())} lines)")


if __name__ == "__main__":
    main()
