"""Render a `nature-review-studio` payload into a single .docx file (V1.4).

V1.4 changes (root-cause fix for blue-underlined English tokens and italic
Heading 4 headings):
  * Force every paragraph style (Normal, Heading 1-4) to have color=000000
    and no italic/underline, and strip any char-style link.
  * Override the built-in Hyperlink character style so it also has
    color=000000 and no underline; this stops Office from auto-painting
    "Methods", "Figure 2", "p-tau217", etc. blue-underlined.
  * Sanitize the payload text before write: strip control chars, replace
    PUA / Specials with [?], and force every word-like run to be black and
    non-underlined at the run level so any character style (Hyperlink,
    Strong, Emphasis) that Office inserts cannot override.
  * No font is forced anywhere; Word and WPS use the system default for
    each script. Bold is reserved for: headings, table header row, the
    "Confidence:" line, task-table ID column, and inline evidence-anchor
    references.
"""
from __future__ import annotations
import os

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

def _nrs_root() -> Path:
    """Locate the nature-review-studio release root.

    Resolution order:
      1. $NRS_ROOT env var (set by install.ps1 or user)
      2. Legacy $NRL_ROOT env var
      3. Walk up from this script to find a sibling `knowledge/`
      4. Legacy: 3 levels up (workspace layout)
    """
    env = os.environ.get("NRS_ROOT") or os.environ.get("NRL_ROOT")
    if env:
        return Path(env).resolve()
    here = Path(__file__).resolve().parent
    for ancestor in [here, *here.parents]:
        if (ancestor / "knowledge" / "cases.jsonl").exists():
            return ancestor
    return here.parents[3]  # legacy workspace fallback

_NRS_ROOT = _nrs_root()
sys.path.insert(0, str(_NRS_ROOT / "scripts" / "python_docx"))

try:
    from docx import Document
    from docx.enum.style import WD_STYLE_TYPE
    from docx.enum.table import WD_ALIGN_VERTICAL
    from docx.shared import Pt
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
except Exception as e:
    print(f"[fatal] python-docx import failed: {e}", file=sys.stderr)
    sys.exit(2)


# ----- Bilingual heading dictionaries -------------------------------

TITLES = {
    "en": {
        "editor_letter_prefix": "Editor letter",
        "reviewer_section": "Reviewer",
        "overall": "Overall",
        "major": "Major concerns",
        "minor": "Minor concerns",
        "consensus": "Cross-review consensus",
        "task_table": "Revision task table",
        "confidence": "Confidence",
        "footer": "Generated by nature-review-studio",
        "no_consensus": "No concerns are shared by >=2 reviewers. Reviewers mostly agreed on small points.",
        "title": "Manuscript review",
    },
    "zh": {
        "editor_letter_prefix": "编辑信",
        "reviewer_section": "审稿人",
        "overall": "整体点评",
        "major": "主要问题",
        "minor": "次要问题",
        "consensus": "跨审稿意见综合",
        "task_table": "修订任务表",
        "confidence": "置信度",
        "footer": "由 nature-review-studio 生成",
        "no_consensus": "没有 >=2 位审稿人共同关心的问题。审稿人之间仅在细节上存在一致。",
        "title": "论文审稿意见",
    },
}

REVISION_BAND_ORDER = {
    "Major revision": ("Major revision", "重大修改"),
    "Accept with minor revisions": ("Accept with minor revisions", "接收（小修）"),
    "Reject in present form": ("Reject in present form", "本稿拒收"),
    "Cannot be assessed": ("Cannot be assessed", "无法评估"),
}
ALLOWED_LEVELS = list(REVISION_BAND_ORDER.keys())


# ----- Mojibake / control sanitizer ---------------------------------

_MOJI_RE = re.compile(r"[\uE000-\uF8FF\uFFF0-\uFFFF]")
_CTRL_RE = re.compile(r"[\u0000-\u0008\u000B-\u001F\u007F]")


def sanitize(text: str) -> str:
    if not text:
        return text
    text = _CTRL_RE.sub("", text)
    text = _MOJI_RE.sub("[?]", text)
    return text


def s(text) -> str:
    if text is None:
        return ""
    return sanitize(str(text))


# ----- Payload lint --------------------------------------------------

def lint_payload(p: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    if p.get("entry") not in ("review", "respond"):
        errors.append("entry must be 'review' or 'respond'")
    if not p.get("case_id"):
        errors.append("case_id is required")
    lang = p.get("language")
    if lang not in ("zh", "en"):
        errors.append("language must be 'zh' or 'en'")
    el = p.get("editor_letter") or {}
    if not el.get("revision_level"):
        errors.append("editor_letter.revision_level is required")
    elif el["revision_level"] not in ALLOWED_LEVELS:
        errors.append(
            "editor_letter.revision_level must be one of " + ", ".join(ALLOWED_LEVELS)
        )
    if not el.get("paragraphs"):
        errors.append("editor_letter.paragraphs is empty (must have >=1 paragraph)")
    reviewers = p.get("reviewers") or []
    if not reviewers:
        errors.append("at least one reviewer is required")
    for i, r in enumerate(reviewers):
        if not r.get("role_label"):
            errors.append(f"reviewers[{i}].role_label is required")
        if not r.get("overall_paragraph"):
            errors.append(f"reviewers[{i}].overall_paragraph is required")
    return errors


# ----- Style reset: zero out every paragraph style's color/italic/underline

def _zero_formatting(rPr):
    """Strip color, italic, underline, and any char-style link from a rPr element."""
    for tag_name in ("color", "i", "iCs", "u", "rStyle"):
        for tag in list(rPr.findall(qn(f"w:{tag_name}"))):
            rPr.remove(tag)
    color = OxmlElement("w:color")
    color.set(qn("w:val"), "000000")
    rPr.append(color)


def _zero_paragraph_formatting(pPr):
    for tag_name in ("rPr",):
        pass  # pPr-level rPr is used for paragraph-mark run; handled separately
    # No paragraph-level color/italic, those live in rPr.
    for tag in list(pPr.findall(qn("w:rPr"))):
        _zero_formatting(tag)


def _reset_style(st):
    """Reset a style to: black, non-italic, non-underlined, no italic-on-headings."""
    # Paragraph-style rPr
    rPr = st.element.find(qn("w:rPr"))
    if rPr is None:
        rPr = OxmlElement("w:rPr")
        st.element.append(rPr)
    _zero_formatting(rPr)
    # rStyle link reference
    for tag in list(st.element.findall(qn("w:link"))):
        st.element.remove(tag)
    # If this is a paragraph style, also zero the pPr/rPr (paragraph-mark)
    pPr = st.element.find(qn("w:pPr"))
    if pPr is not None:
        pPr_rPr = pPr.find(qn("w:rPr"))
        if pPr_rPr is not None:
            _zero_formatting(pPr_rPr)


def setup_styles(doc) -> None:
    """Reset every style we use to: black, non-italic, non-underlined. Set
    heading sizes and bold. Also rewrite the built-in Hyperlink character
    style so it is black and non-underlined (kills Office auto-hyperlink
    blue-underline effect on Methods / Figure 2 / p-tau217 etc.)."""
    # 1) Reset Normal and Heading 1-4 paragraph styles
    for name in ("Normal", "Heading 1", "Heading 2", "Heading 3", "Heading 4"):
        try:
            st = doc.styles[name]
        except KeyError:
            continue
        _reset_style(st)

    # 2) Set sizes and bold on headings
    sizes = [("Heading 1", 16), ("Heading 2", 13),
             ("Heading 3", 11), ("Heading 4", 11)]
    for name, size in sizes:
        st = doc.styles[name]
        st.font.size = Pt(size)
        st.font.bold = True

    # 3) Override the built-in Hyperlink character style so it has black, no underline
    try:
        link = doc.styles["Hyperlink"]
    except KeyError:
        # Create it
        link = doc.styles.add_style("Hyperlink", WD_STYLE_TYPE.CHARACTER)
    _reset_style(link)
    # Force: no underline, black color
    rPr = link.element.find(qn("w:rPr"))
    if rPr is None:
        rPr = OxmlElement("w:rPr")
        link.element.append(rPr)
    for tag in list(rPr.findall(qn("w:u"))):
        rPr.remove(tag)
    u = OxmlElement("w:u")
    u.set(qn("w:val"), "none")
    rPr.append(u)
    for tag in list(rPr.findall(qn("w:color"))):
        rPr.remove(tag)
    c = OxmlElement("w:color")
    c.set(qn("w:val"), "000000")
    rPr.append(c)


# ----- Run-level format helpers --------------------------------------

def _force_plain(run):
    """Force a run to be black, non-italic, non-underlined. Counteracts
    Hyperlink / Strong / Emphasis character styles that Office auto-applies."""
    rPr = run._element.get_or_add_rPr()
    for tag_name in ("rStyle", "i", "iCs", "u"):
        for tag in list(rPr.findall(qn(f"w:{tag_name}"))):
            rPr.remove(tag)
    for tag in list(rPr.findall(qn("w:color"))):
        rPr.remove(tag)
    c = OxmlElement("w:color")
    c.set(qn("w:val"), "000000")
    rPr.append(c)
    u = OxmlElement("w:u")
    u.set(qn("w:val"), "none")
    rPr.append(u)


def add_heading(doc, level: int, text: str):
    p = doc.add_paragraph(style=f"Heading {level}")
    run = p.add_run(s(text))
    _force_plain(run)
    run.bold = True
    return p


def add_para(doc, text: str, *, style: str = "Normal"):
    p = doc.add_paragraph(style=style)
    run = p.add_run(s(text))
    _force_plain(run)
    return p


def add_numbered_concern(doc, idx: int, heading: str, body: str, *, evidence_anchor=None):
    add_heading(doc, 4, f"{idx}. {s(heading).rstrip(':.。 ')}")
    p = doc.add_paragraph(style="Normal")
    run = p.add_run(s(body))
    _force_plain(run)
    if evidence_anchor:
        sep = " "
        b = (body or "").rstrip()
        if b and b[-1] not in (".", "。", "!", "?"):
            sep = ". "
        sep_run = p.add_run(sep)
        _force_plain(sep_run)
        run = p.add_run(s(evidence_anchor))
        _force_plain(run)
        run.bold = True
        run.italic = True


def add_consensus_block(doc, consensus, lang: str):
    add_heading(doc, 2, TITLES[lang]["consensus"])
    if not consensus:
        add_para(doc, TITLES[lang]["no_consensus"])
        return
    for c in consensus:
        cid = s(c.get("id", "")).strip()
        desc = s(c.get("description", "")).strip()
        add_heading(doc, 4, f"{cid}. {desc}")
        meta = []
        if c.get("raised_by"):
            rb = ", ".join(s(x) for x in c["raised_by"])
            meta.append(f"raised by: {rb}" if lang == "en" else f"由以下审稿人提出: {rb}")
        if c.get("axis"):
            meta.append(f"axis: {s(c['axis'])}" if lang == "en" else f"轴: {s(c['axis'])}")
        if c.get("severity"):
            meta.append(f"severity: {s(c['severity'])}" if lang == "en" else f"严重程度: {s(c['severity'])}")
        if meta:
            add_para(doc, "  ·  ".join(meta))
        if c.get("rationale"):
            add_para(doc, s(c["rationale"]))
        spacer = doc.add_paragraph(style="Normal")
        sr = spacer.add_run("")
        _force_plain(sr)


def add_table(doc, headers, rows, lang: str):
    tbl = doc.add_table(rows=1 + len(rows), cols=len(headers))
    tbl.style = "Table Grid"
    for j, h in enumerate(headers):
        cell = tbl.rows[0].cells[j]
        cell.text = ""
        p = cell.paragraphs[0]
        p.style = doc.styles["Normal"]
        run = p.add_run(s(h))
        _force_plain(run)
        run.bold = True
        cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER
    for i, row in enumerate(rows, start=1):
        for j, val in enumerate(row):
            cell = tbl.rows[i].cells[j]
            cell.text = ""
            p = cell.paragraphs[0]
            p.style = doc.styles["Normal"]
            run = p.add_run(s(val))
            _force_plain(run)
            if j == 0 and re.match(r"^T\d+$", str(val).strip()):
                run.bold = True
            cell.vertical_alignment = WD_ALIGN_VERTICAL.CENTER


def add_footer(doc, case_id: str, lang: str):
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.style = doc.styles["Normal"]
    today = datetime.now().strftime("%Y-%m-%d")
    run = p.add_run(f"{TITLES[lang]['footer']}  ·  {today}  ·  {case_id}")
    _force_plain(run)
    run.italic = True
    run.font.size = Pt(9)


# ----- Top-level render ---------------------------------------------

def render(payload: Dict[str, Any], out_path: Path) -> None:
    entry = payload["entry"]
    case_id = payload["case_id"]
    lang = payload["language"]
    T = TITLES[lang]

    doc = Document()
    setup_styles(doc)

    add_heading(doc, 1, T["title"])
    sub = doc.add_paragraph(style="Normal")
    run = sub.add_run(f"Case: {case_id}")
    _force_plain(run)
    run.italic = True
    doc.add_paragraph()

    el = payload["editor_letter"]
    band = el["revision_level"]
    band_disp = REVISION_BAND_ORDER[band][0 if lang == "en" else 1]
    add_heading(doc, 2, f"{T['editor_letter_prefix']} — {band_disp}")
    for para in el["paragraphs"]:
        if not para or not para.strip():
            continue
        add_para(doc, para)

    reviewers = payload["reviewers"]
    for i, r in enumerate(reviewers):
        add_heading(doc, 2, f"{T['reviewer_section']} {chr(ord('A') + i)} — {s(r['role_label'])}")
        add_heading(doc, 3, T["overall"])
        add_para(doc, r["overall_paragraph"])

        majors = r.get("major_concerns") or []
        if majors:
            add_heading(doc, 3, T["major"])
            for idx, c in enumerate(majors, start=1):
                anchor = c.get("evidence_pointer") or None
                if anchor:
                    add_numbered_concern(doc, idx, c.get("heading", ""), c.get("body", ""),
                                         evidence_anchor=anchor)
                else:
                    add_numbered_concern(doc, idx, c.get("heading", ""), c.get("body", ""))

        minors = r.get("minor_concerns") or []
        if minors:
            add_heading(doc, 3, T["minor"])
            for idx, c in enumerate(minors, start=1):
                anchor = c.get("evidence_pointer") or None
                if anchor:
                    add_numbered_concern(doc, idx, c.get("heading", ""), c.get("body", ""),
                                         evidence_anchor=anchor)
                else:
                    add_numbered_concern(doc, idx, c.get("heading", ""), c.get("body", ""))

        if r.get("overall_confidence"):
            p = doc.add_paragraph(style="Normal")
            run = p.add_run(f"{T['confidence']}: {s(r['overall_confidence'])}.")
            _force_plain(run)
            run.bold = True

    add_consensus_block(doc, payload.get("consensus_block") or [], lang)

    tt = payload.get("revision_task_table") or {}
    if tt and tt.get("headers") and tt.get("rows"):
        add_heading(doc, 2, T["task_table"])
        add_table(doc, tt["headers"], tt["rows"], lang)

    add_footer(doc, case_id, lang)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(out_path)


# ----- Entry point ---------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--payload", required=True)
    ap.add_argument("--out", default=None, help="output .docx path (default: build/output/<entry>_<case>_<date>.docx)")
    ap.add_argument("--md-out", default=None, help="companion .md path (default: same stem as --out)")
    ap.add_argument("--language", default=None)
    args = ap.parse_args()

    with open(args.payload, "rb") as f:
        raw = f.read()
    if raw[:3] == b"\xef\xbb\xbf":
        raw = raw[3:]
    payload = json.loads(raw.decode("utf-8"))

    if args.language:
        payload["language"] = args.language

    errors = lint_payload(payload)
    if errors:
        print("[lint-fail] " + "; ".join(errors), file=sys.stderr)
        sys.exit(1)

    today = datetime.now().strftime("%Y%m%d")
    default_dir = _NRS_ROOT / "output"
    if not args.out:
        args.out = str(default_dir / (payload["entry"] + "_" + payload["case_id"] + "_" + today + ".docx"))
    if not args.md_out:
        args.md_out = str(Path(args.out).with_suffix(".md"))

    docx_path = Path(args.out)
    render(payload, docx_path)

    from render_review_md import render_markdown
    md_text = render_markdown(payload)
    md_path = Path(args.md_out)
    md_path.parent.mkdir(parents=True, exist_ok=True)
    md_path.write_text(md_text, encoding="utf-8")
    md_msg = " + " + str(md_path) + "  (" + str(len(md_text)) + " chars)"

    reviewers = payload.get("reviewers", [])
    print(
        "[ok] wrote " + str(docx_path) + md_msg + "  ("
        + str(len(reviewers)) + " reviewers, lang=" + str(payload["language"])
        + ", band=" + str(payload["editor_letter"]["revision_level"]) + ")"
    )


if __name__ == "__main__":
    main()
